# Generated by Django 2.2.14 on 2021-10-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='toit_ouvrant',
            field=models.BooleanField(default=False),
        ),
    ]
