# Generated by Django 2.2.14 on 2021-10-31 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_voiture_toit_ouvrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='photo_option2',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voiture',
            name='toit_ouvrant',
            field=models.BooleanField(default=True),
        ),
    ]
