# Generated by Django 2.2.14 on 2021-10-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211031_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='photo_option2',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
