# Generated by Django 2.2.14 on 2021-12-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_voiture_my_field'),
        ('app', '0005_voiture_opt'),
    ]

    operations = [
    ]
