# Generated by Django 2.2.14 on 2021-12-23 10:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20211223_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='my_field',
        ),
        migrations.AlterField(
            model_name='voiture',
            name='opt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Ecran de bord'), (2, 'Camera de recule'), (3, 'Demarrage start/Stop'), (4, 'Toit panoramique'), (5, 'Abs')], max_length=9),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_option2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
