# Generated by Django 2.2.14 on 2021-12-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211223_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='photo_arriere',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_assurance',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_carte_grise',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_defaut1',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_defaut2',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_defaut3',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_defaut4',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_defaut5',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_face',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_longueur1',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_longueur2',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_moteur',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_option1',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_option3',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_option4',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_option5',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_tableau',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
    ]
