# Generated by Django 2.2.14 on 2021-12-24 12:51

from django.db import migrations
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211223_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='opt',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='photo_defaut1',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='photo_defaut2',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='photo_defaut3',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='photo_defaut4',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='photo_defaut5',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='photo_option4',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='photo_option5',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='toit_ouvrant',
        ),
        migrations.AddField(
            model_name='voiture',
            name='option',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Ecran de bord'), (2, 'Camera de recule'), (3, 'Demarrage start/Stop'), (4, 'Toit panoramique'), (5, 'Abs'), (6, 'Capteur avant et arrière'), (7, 'siège ventilé'), (8, 'siège climatisé')], default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
