# Generated by Django 2.2.14 on 2021-12-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211224_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='date_ajouts',
            new_name='date_ajout',
        ),
    ]
