# Generated by Django 2.2.14 on 2022-01-05 22:06

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211224_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='option',
        ),
        migrations.AddField(
            model_name='voiture',
            name='opt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Ecran de bord'), (2, 'Camera de recule'), (3, 'Demarrage start/Stop'), (4, 'Toit panoramique'), (5, 'Abs'), (6, 'Capteur avant et arrière'), (7, 'siège ventilé'), (8, 'siège climatisé')], default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voiture',
            name='annee',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)]),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_arriere',
            field=models.ImageField(blank=True, default='/static/images/logo-light.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_assurance',
            field=models.ImageField(blank=True, default='/static/images/logo-light.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_carte_grise',
            field=models.ImageField(blank=True, default='/static/images/logo-light.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_face',
            field=models.ImageField(blank=True, default='/static/images/logo-light.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_longueur1',
            field=models.ImageField(blank=True, default='/static/images/logo-light.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_longueur2',
            field=models.ImageField(blank=True, default='/static/images/logo-light.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_moteur',
            field=models.ImageField(blank=True, default='/static/images/logo-light.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_option1',
            field=models.ImageField(blank=True, default='/static/images/logo-light.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_option2',
            field=models.ImageField(blank=True, default='/static/images/logo-light.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_option3',
            field=models.ImageField(blank=True, default='/static/images/logo-light.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_tableau',
            field=models.ImageField(blank=True, default='/static/images/logo-light.png', null=True, upload_to='images/'),
        ),
    ]
