# Generated by Django 2.2.14 on 2022-01-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220106_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='photo_assurance',
            field=models.ImageField(blank=True, default='app/static/images/logo-light.png', null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_carte_grise',
            field=models.ImageField(blank=True, default='app/static/images/logo-light.png', null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_moteur',
            field=models.ImageField(blank=True, default='app/static/images/logo-light.png', null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_option1',
            field=models.ImageField(blank=True, default='app/static/images/logo-light.png', null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_option2',
            field=models.ImageField(blank=True, default='app/static/images/logo-light.png', null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_option3',
            field=models.ImageField(blank=True, default='app/static/images/logo-light.png', null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo_tableau',
            field=models.ImageField(blank=True, default='app/static/images/logo-light.png', null=True, upload_to='media/images/'),
        ),
    ]
