# Generated by Django 2.2.14 on 2022-01-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220106_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=225)),
                ('message', models.TextField()),
            ],
        ),
    ]
